# References all the .rb files in the vm folder
require_files = []

require_files << File.join(File.dirname(__FILE__), "../vm", "core.rb") # => ["./../vm/core.rb"]
require_files << File.join(File.dirname(__FILE__), "../vm", "helpers.rb") # => ["./../vm/core.rb", "./../vm/helpers.rb"]
require_files << File.join(File.dirname(__FILE__), "../vm", "exceptions.rb") # => ["./../vm/core.rb", "./../vm/helpers.rb", "./../vm/exceptions.rb"]
require_files.concat Dir[File.join(File.dirname(__FILE__), '../vm', '**', '*.rb')] # => ["./../vm/core.rb", "./../vm/helpers.rb", "./../vm/exceptions.rb", "./../vm/accessors.rb", "./../vm/core.rb", "./../vm/exceptions.rb", "./../vm/helpers.rb", "./../vm/opcodes/_opcode_constants.rb", "./../vm/opcodes/_value_constants.rb", "./../vm/opcodes/comparative_operations/equal.rb", "./../vm/opcodes/comparative_operations/greater_than.rb", "./../vm/opcodes/comparative_operations/greaterEq.rb", "./../vm/opcodes/comparative_operations/invert.rb", "./../vm/opcodes/comparative_operations/less_than.rb", "./../vm/opcodes/comparative_operations/lessEq.rb", "./../vm/opcodes/control_operations/exit.rb", "./../vm/opcodes/control_operations/no_op.rb", "./../vm/opcodes/flow_control_operations/jump.rb", "./../vm/opcodes/flow_control_operations/jump_if.rb", "./../vm/opcodes/flow_control_operations/jump_unless.rb", "./../vm/opcodes/function_operations/call.rb", "./../vm/opcodes/function_operations/push_function.rb", "./../vm/opcodes/function_operations/return.rb", "./../vm/opcodes/function_operations/tailcall.rb", "./../vm/opcodes/hash_operations/get_key.rb", "./../vm/opcodes/hash_operations/has_key.rb", "./../vm/opcodes/hash_operations/length.rb", "./../vm/opcodes/hash_operations/num_pairs.rb", "./../vm/opcodes/hash_operations/pairs.rb", "./../vm/opcodes/hash_operations/push_hash.rb", "./../vm/opcodes/hash_operations/set_key.rb", "./../vm/opcodes/io_operations/gets.rb", "./../vm/opcodes/io_operations/print.rb", "./../vm/opcodes/math_operations/add.rb", "./../vm/opcodes/math_operations/divide.rb", "./../vm/opcodes/math_operations/multiply.rb", "./../vm/opcodes/math_operations/subtract.rb", "./../vm/opcodes/push_operations/push_bool.rb", "./../vm/opcodes/push_operations/push_char.rb", "./../vm/opcodes/push_operations/push_float.rb", "./../vm/opcodes/push_operations/push_int.rb", "./../vm/opcodes/push_operations/push_nil.rb", "./../vm/opcodes/push_operations/push_string.rb", "./../vm/opcodes/stack_operations/dup.rb", "./../vm/opcodes/stack_operations/pop.rb", "./../vm/opcodes/stack_operations/stksize.rb", "./../vm/opcodes/stack_operations/swap.rb", "./../vm/opcodes/stack_operations/top.rb", "./../vm/opcodes/stack_operations/typeof.rb", "./../vm/opcodes/string_operations/concat.rb", "./../vm/opcodes/string_operations/strlen.rb", "./../vm/opcodes/string_operations/to_string.rb", "./../vm/opcodes/variable_operations/get_global.rb", "./../vm/opcodes/variable_operations/get_local.rb", "./../vm/opcodes/variable_operations/set_global.rb", "./../vm/opcodes/variable_operations/set_local.rb"]

require_files.each do |file|
  require File.expand_path(file)
end
# >> 5
